
[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "Hack Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Medium Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Medium"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.95

[mouse]
hide_when_typing = true  # Default: false

[colors.primary]
foreground = "#e5e5e5"
background = "#262a33"
dim_foreground = "#ece7e7"
bright_foreground = "None"

[colors.normal]
black = "#000000"
red = "#cd3131"
green = "#05bc79"
yellow = "#e5e512"
blue = "#2472c8"
magenta = "#bc3fbc"
cyan = "#0fa8cd"
white = "#e5e5e5"

[colors.bright]
black = "#666666"
red = "#cd3131"
green = "#05bc79"
yellow = "#e5e512"
blue = "#2472c8"
magenta = "#bc3fbc"
cyan = "#0fa8cd"
white = "#e5e5e5"

[colors.dim]
black = "#000000"
red = "#cd3131"
green = "#05bc79"
yellow = "#e5e512"
blue = "#2472c8"
magenta = "#bc3fbc"
cyan = "#0fa8cd"
white = "#e5e5e5"

[general]
live_config_reload = true
